import com.android.build.gradle.tasks.ExternalNativeBuildTask

apply plugin: 'com.android.application'

def appId = project.hasProperty('hx90vPackage')
        ? 'com.github.ma1co.openmemories.tweak.hx90v'
        : 'com.github.ma1co.openmemories.tweak'

android {
    compileSdkVersion 10

    defaultConfig {
        applicationId appId
        minSdkVersion 10
        targetSdkVersion 10
        versionCode "git -C ${projectDir} rev-list --first-parent --count HEAD".execute().text.trim().toInteger()
        versionName "git -C ${projectDir} describe --always --tags --dirty".execute().text.trim().replaceAll("^v", "")
        if (!project.hasProperty('usePrebuiltNative')) {
            externalNativeBuild {
                ndkBuild {
                    abiFilters 'armeabi'
                    targets 'tweak', 'adbd'
                }
            }
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    if (!project.hasProperty('usePrebuiltNative')) {
        externalNativeBuild {
            ndkBuild {
                path 'src/main/jni/Android.mk'
            }
        }
    }

    packagingOptions {
        // Whitelist for libraries
        pickFirst 'lib/armeabi/libtweak.so'
        pickFirst 'lib/armeabi/libprotectiontweak.so'
        pickFirst 'lib/armeabi/libadbd.so'
        exclude 'lib/armeabi/*.so'
    }

    sourceSets.main {
        jniLibs.srcDir project.hasProperty('usePrebuiltNative') ? 'src/main/prebuilt-jniLibs' : "$buildDir/libs"
    }
}

task runMake(type: Exec) {
    // This will compile the backupsetid1 executable that can be run outside the chrooted android
    // environment
    executable = 'make'
    args = ["-C", "$projectDir/src/main/jni", "BUILDDIR=$buildDir/platform"]
}

if (!project.hasProperty('usePrebuiltNative')) {
    tasks.withType(ExternalNativeBuildTask) {
        dependsOn runMake
        doLast {
            copy {
                // Rename executables to lib*.so, so android will unpack them for us during installation
                from files(
                        "$buildDir/platform/protectiontweak",
                        new File(objFolder, "armeabi/adbd"),
                )
                into "$buildDir/libs/armeabi"
                rename { fn -> "lib${fn}.so" }
            }
        }
    }
} else {
    tasks.matching { it.name ==~ /compile.*Ndk/ }.all {
        enabled = false
    }
}
